---
catalyst_center_hosts:
  hosts:
    catalyst_center53:
      #catalyst_center_password: "C1sco#123!"
      catalyst_center_password: "Maglev123"
      #catalyst_center_host: 10.195.243.53
      catalyst_center_host: 10.195.243.38
      catalyst_center_port: 443
      catalyst_center_timeout: 300
      catalyst_center_username: admin
      catalyst_center_version: 2.3.7.9
      catalyst_center_verify: false
      catalyst_center_debug: true
      catalyst_center_log_level: DEBUG
      catalyst_center_log: true
      catalyst_center_log_append: false
      catalyst_center_log_file_path: "dnac_log.log"
      catalyst_center_api_task_timeout: 1200
